# Generated by Django 4.1.3 on 2022-11-20 11:17

from django.db import migrations, models
import principal.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[(principal.models.ProductType['FUND'], 'Funda'), (principal.models.ProductType['CARG'], 'Cargadores'), (principal.models.ProductType['PROT'], 'Protectores'), (principal.models.ProductType['OTRO'], 'Otros')], default=principal.models.ProductType['OTRO'], max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='secciones',
            field=models.CharField(choices=[(principal.models.ProductSections['HUWI'], 'Huawei'), (principal.models.ProductSections['XIAO'], 'Xiaomi'), (principal.models.ProductSections['SAMG'], 'Samsung'), (principal.models.ProductSections['VIVO'], 'Vivo'), (principal.models.ProductSections['UNK'], 'Desconocido')], default=principal.models.ProductSections['UNK'], max_length=15),
        ),
    ]
