# Generated by Django 4.1.3 on 2022-11-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_cestaitem_alter_cesta_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='items',
            field=models.ManyToManyField(to='principal.producto'),
        ),
        migrations.DeleteModel(
            name='CestaItem',
        ),
    ]
