# Generated by Django 4.1.3 on 2022-11-26 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_cestaitem_alter_cesta_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cestaitem',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
