# Generated by Django 4.1.1 on 2022-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_cesta_usuario_remove_cesta_items_cesta_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='items',
        ),
        migrations.AddField(
            model_name='cesta',
            name='items',
            field=models.ManyToManyField(to='principal.cestaitem'),
        ),
    ]
