# Generated by Django 4.1.3 on 2022-11-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_remove_cesta_items_cesta_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cestaitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.producto'),
        ),
    ]
