# Generated by Django 4.1.1 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cesta',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cestaItem',
            field=models.ManyToManyField(to='principal.cestaitem'),
        ),
    ]
