# Generated by Django 4.1.1 on 2022-11-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_remove_pedido_cesta_pedido_cestaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
    ]
