# Generated by Django 4.1.1 on 2022-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_remove_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
