# Generated by Django 4.1.1 on 2022-11-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
