# Generated by Django 4.1.3 on 2022-12-02 15:40

import django.core.validators
from django.db import migrations, models
import principal.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_delete_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default=principal.models.EstadoPedido['PEND'], max_length=15),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lugar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plazo',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
