# Generated by Django 4.1.3 on 2022-12-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_pedido_estado_pedido_lugar_pedido_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='saveInfo',
            field=models.BooleanField(default=False),
        ),
    ]
